controller:
  serviceType: LoadBalancer
  
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - git-client
    - github
  installLatestPlugins: true

  ingress:
    enabled: true
    ingressClassName: nginx
    className: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"

    hostName: jenkins.pedersen.io
    path: /
    pathType: ImplementationSpecific

    tls:
      - secretName: jenkins-pedersen-io-tls
        hosts:
          - jenkins.pedersen.io

  env:
    - name: CASC_JENKINS_CONFIG
      value: /var/jenkins_home/jenkins-casc.yaml

  JCasC:
    configScripts:
      jenkins-casc.yaml: |-
        jenkins:
          systemMessage: "Jenkins managed by CasC"
          numExecutors: 0
          mode: NORMAL
          scmCheckoutRetryCount: 2

          clouds:
          - kubernetes:
              name: "kubernetes"
              namespace: "jenkins"
              templates:
              - containers:
                - alwaysPullImage: true
                  args: "^${computer.jnlpmac} ^${computer.name}"
                  image: "derekpedersen/build-golang:latest"
                  livenessProbe:
                    failureThreshold: 0
                    initialDelaySeconds: 0
                    periodSeconds: 0
                    successThreshold: 0
                    timeoutSeconds: 0
                  name: "jnlp"
                  resourceLimitCpu: ".5"
                  resourceLimitMemory: "512Mi"
                  resourceRequestCpu: ".1"
                  resourceRequestMemory: "512Mi"
                  workingDir: "/home/jenkins"
                id: "e4a18b6c-8e74-498c-adad-53d145c92728"
                idleMinutes: 15
                idleMinutesStr: "15"
                instanceCap: 5
                instanceCapStr: "5"
                label: "build-golang-stable"
                name: "golang"
                nodeUsageMode: "NORMAL"
                podRetention: "onFailure"
                serviceAccount: "default"
                slaveConnectTimeout: 600
                slaveConnectTimeoutStr: "600"
                volumes:
                - hostPathVolume:
                    hostPath: "/var/run/docker.sock"
                    mountPath: "/var/run/docker.sock"
                yamlMergeStrategy: "override"
              - containers:
                - alwaysPullImage: true
                  args: "^${computer.jnlpmac} ^${computer.name}"
                  image: "derekpedersen/build-node:latest"
                  livenessProbe:
                    failureThreshold: 0
                    initialDelaySeconds: 0
                    periodSeconds: 0
                    successThreshold: 0
                    timeoutSeconds: 0
                  name: "jnlp"
                  ttyEnabled: true
                  workingDir: "/home/jenkins"
                id: "6170664b-ab08-46ae-a41d-a2721b714a12"
                idleMinutes: 15
                idleMinutesStr: "15"
                instanceCap: 5
                instanceCapStr: "5"
                label: "build-node-stable"
                name: "node"
                podRetention: "onFailure"
                slaveConnectTimeout: 600
                slaveConnectTimeoutStr: "600"
                volumes:
                - hostPathVolume:
                    hostPath: "/var/run/docker.sock"
                    mountPath: "/var/run/docker.sock"
                yamlMergeStrategy: "override"
              - containers:
                - alwaysPullImage: true
                  args: "^${computer.jnlpmac} ^${computer.name}"
                  image: "derekpedersen/build-jenkins-base:latest"
                  livenessProbe:
                    failureThreshold: 0
                    initialDelaySeconds: 0
                    periodSeconds: 0
                    successThreshold: 0
                    timeoutSeconds: 0
                  name: "jnlp"
                  ttyEnabled: true
                  workingDir: "/home/jenkins/agent"
                id: "02b8986f-3c2b-46a9-9b2a-00ba2e83cc4e"
                idleMinutes: 15
                idleMinutesStr: "15"
                instanceCap: 5
                instanceCapStr: "5"
                label: "build-base-stable"
                name: "jenkins"
                podRetention: "onFailure"
                slaveConnectTimeout: 600
                slaveConnectTimeoutStr: "600"
                volumes:
                - hostPathVolume:
                    hostPath: "/var/run/docker.sock"
                    mountPath: "/var/run/docker.sock"
                yamlMergeStrategy: "override"
              - containers:
                - alwaysPullImage: true
                  args: "^${computer.jnlpmac} ^${computer.name}"
                  image: "derekpedersen/build-dotnetcore:latest"
                  livenessProbe:
                    failureThreshold: 0
                    initialDelaySeconds: 0
                    periodSeconds: 0
                    successThreshold: 0
                    timeoutSeconds: 0
                  name: "jnlp"
                  ttyEnabled: true
                  workingDir: "/home/jenkins"
                id: "6170664b-ab08-46ae-a41d-a2721b714a12"
                idleMinutes: 15
                idleMinutesStr: "15"
                instanceCap: 5
                instanceCapStr: "5"
                label: "build-dotnetcore-stable"
                name: "dotnetcore"
                podRetention: "onFailure"
                slaveConnectTimeout: 600
                slaveConnectTimeoutStr: "600"
                volumes:
                - hostPathVolume:
                    hostPath: "/var/run/docker.sock"
                    mountPath: "/var/run/docker.sock"
                yamlMergeStrategy: "override"

        unclassified:
          location:
            adminAddress: "admin@example.com"
            url: "https://jenkins.pedersen.io/"

  imagePullSecrets:
    - name: regcred

persistence:
  enabled: true
  size: 8Gi